### ISSUE TITLE
Understanding number of features?

### ISSUE THREAD

**Issue by eric-tc** [blackfeather-wang/ISDA-for-Deep-Networks#1]
Hi thanks for sharing the code. I had a look and i cannot understand why in ./networks/resnet.py at line 169 the value of self.feature_num=64 is the same for all model and instead for wideresnet and other networks the value is different.

Thanks

**Comment by blackfeather-wang** [comment]
Hi, thanks for visiting this repository.

Self.feature_num corresponds to the number of dimensions of deep features obtained from the network, which is usually determined by the width of the model, and differs among different network structures. Basic ResNets for CIFAR share the same width while differ in depth. That's why self.feature_num remains the same.

Sincerely, Yulin Wang.

**Comment by eric-tc** [comment]
ok now it is clear.

Thanks
